//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteOrder.db_context
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.SampleSitesGroup = new HashSet<SampleSitesGroup>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public int technicalTaskId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleSitesGroup> SampleSitesGroup { get; set; }
        public virtual TechnicalTask TechnicalTask { get; set; }

        public List<SampleSite> SampleSites
        {
            get
            {
                return SampleSitesGroup.Select(v => v.SampleSite).ToList();
            }
        }

        public override string ToString()
        {
            return this.name;
        }
    }
}
