//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteOrder.db_context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logbook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Logbook()
        {
            this.LayoutAccess = new HashSet<LayoutAccess>();
        }
    
        public int id { get; set; }
        public int technicalTaskId { get; set; }
        public string userLogin { get; set; }
        public string userType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayoutAccess> LayoutAccess { get; set; }
        public virtual TechnicalTask TechnicalTask { get; set; }
        public virtual User User { get; set; }
    }
}
