//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteOrder.db_context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleSitesGroup
    {
        public int id { get; set; }
        public int sampleSiteId { get; set; }
        public int demandId { get; set; }
        public string note { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual SampleSite SampleSite { get; set; }
    }
}
