//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteOrder.db_context
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SiteLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteLayout()
        {
            this.LayoutAccess = new HashSet<LayoutAccess>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string fileName { get; set; }
        public bool isPublic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayoutAccess> LayoutAccess { get; set; }

        public String FileName
        {
            get
            {
                if (
                fileName == null ||
                String.IsNullOrWhiteSpace(fileName) ||
                !System.IO.File.Exists(fileName)
                )
                {
                    return null;
                }
                return fileName;
            }
        }

        public String Owner
        {
            get
            {
                var ownerList = this.LayoutAccess.ToList().Where(v => v.isOwner).Select(v => v.Logbook).Select(v => v.User).Distinct();
                if (ownerList.Count() == 0)
                {
                    return "Владельца нет!";
                }
                String result = ownerList.First().ToString();
                if (ownerList.Count() != 1)
                {
                    result += " и другие...";
                }
                return result;
            }
        }
    }
}
