//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteOrder.db_context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class SitesCreateEntities : DbContext
    {
        private static SitesCreateEntities _context;

        public static SitesCreateEntities GetContext()
        {
            if (_context == null)
            {
                _context = new SitesCreateEntities();
            }
            return _context;
        }

        public void ClearStateAndReloadAll()
        {
            this.ChangeTracker.Entries().ToList().Where(v => v.State == EntityState.Added ||
            v.State == EntityState.Modified ||
            v.State == EntityState.Deleted).ToList().ForEach(v => v.State = EntityState.Detached);
            this.ChangeTracker.Entries().ToList().ForEach(v => v.Reload());
        }

        public SitesCreateEntities()
            : base("name=SitesCreateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Demand> Demand { get; set; }
        public virtual DbSet<LayoutAccess> LayoutAccess { get; set; }
        public virtual DbSet<Logbook> Logbook { get; set; }
        public virtual DbSet<SampleSitesGroup> SampleSitesGroup { get; set; }
        public virtual DbSet<SiteLayout> SiteLayout { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechnicalTask> TechnicalTask { get; set; }
        public virtual DbSet<SampleSite> SampleSite { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
